---
- hosts: localhost
  connection: local
  become: true


  tasks:
  - name: install packages
    package:
      name: 
       - htop
       - tmux

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/gmm/.bashrc
      owner: gmm
      group: gmm

